services:
  - type: web
    name: tarukoda-api
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /up
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        sync: false
      - key: DB_CONNECTION
        value: sqlite
      - key: HASH_DRIVER
        value: argon2id
      - key: JWT_SECRET
        generateValue: true
      - key: MAIL_MAILER
        value: smtp
      - key: MAIL_HOST
        sync: false
      - key: MAIL_PORT
        value: 587
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: MAIL_FROM_ADDRESS
        value: info@tarukoda.ee
      - key: MAIL_TO
        sync: false
      - key: STRIPE_KEY
        sync: false
      - key: STRIPE_SECRET
        sync: false
